[build]
target = "x86_64-unknown-none"
rustflags = [
    "-Zunstable-options",
    "-Crelocation-model=pie",
#    "-Crelocation-model=static",
#    "-Cprefer-dynamic=no",
    "-Ctarget-feature=+crt-static",
#    "-Clink-self-contained=yes",
#    "-Clink-arg=-Bstatic",
#    "-Clink-arg=--Bsymbolic",
#    "-Clink-arg=--Bsymbolic-functions",
    "-Clink-arg=-image-base=0",
#    "-Clink-arg=-image-base=0x18000",
#    "-Clink-arg=--no-dynamic-linker",
#    "-Clink-arg=--apply-dynamic-relocs",
#    "-Clink-arg=--print-map"
#    "-Clink-arg=--no-pie",
#    "-Clink-arg=--disable-new-dtags",
#    "-Clink-arg=--discard-all",
#    "-Clink-arg=-zinitfirst",
#    "-Clink-arg=-znognustack",
#    "-Clink-args=--no-pic-executable"
    #"-Clink-arg=--crash"
#    "--emit", "llvm-ir"
]

[unstable]
build-std = ["core"]
