unstable_features = true
edition = "2021"
version = "Two"

binop_separator = "Back"

brace_style = "AlwaysNextLine"

condense_wildcard_suffixes = true

enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

fn_single_line = true

format_macro_matchers = true

format_strings = true

hex_literal_case = "Lower"

imports_layout = "HorizontalVertical"

match_block_trailing_comma = true

imports_granularity = "Crate"

overflow_delimited_expr = true

group_imports = "StdExternalCrate"

trailing_comma = "Never"

use_field_init_shorthand = true

use_try_shorthand = true

where_single_line = true

wrap_comments = true
